version: "3.7"
services:
  api:
    container_name: "wedding-api"
    build: .
    ports: 
      - 3000:3000
  db: 
    container_name: wedding-db
    image: postgres:latest
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: wedding-db
      DB_HOST: localhost
      INTERNAL_DB_PORT: 5434
      NODE_ENV: development
    ports: 
      - 5434:5432
  # volumes:
  #   # Bind mount local directory to dev, ignoring node modules 
  #     - ./:./app
